import type {
  ApplianceType,
  BroadCategory,
  TaskStatus,
  RepairStatus,
} from './enums';
import type { RepairState, StateId } from './state-machine';

// ---- Auth ----
export interface LoginRequest {
  /** Google ID token from Expo AuthSession / Google Sign-In. */
  idToken: string;
}

export interface LoginResponse {
  accessToken: string;
  refreshToken: string;
  user: UserDto;
}

export interface RefreshRequest {
  refreshToken: string;
}

export interface UserDto {
  id: string;
  email: string;
  name: string | null;
  avatarUrl: string | null;
}

// ---- Rooms ----
export interface RoomDto {
  id: string;
  name: string;
  applianceCount: number;
  /** Any appliance image in this room (for UI preview). */
  previewImageUrl?: string | null;
  /** Count of outstanding maintenance tasks for appliances in this room. */
  openMaintenanceCount?: number;
  createdAt: string;
}

export interface CreateRoomRequest {
  name: string;
}

// ---- Appliances ----
export interface ApplianceDto {
  id: string;
  roomId: string;
  type: ApplianceType;
  brand: string | null;
  model: string | null;
  nickname: string | null;
  installedAt: string | null;
  primaryImageUrl: string | null;
  /** Count of outstanding maintenance tasks for this appliance. */
  openMaintenanceCount?: number;
  createdAt: string;
}

export interface ApplianceDetailDto extends ApplianceDto {
  images: { id: string; url: string; createdAt: string }[];
  upcomingTasks: MaintenanceTaskDto[];
  recentRepairs: { id: string; status: RepairStatus; startedAt: string }[];
}

export interface RegisterFromImageRequest {
  roomId: string;
  /** Either a public URL we can fetch or a base64 data URL. The mobile client uploads to S3 first and sends the resulting URL. */
  imageUrl: string;
  nickname?: string;
}

export interface RegisterFromImageResponse {
  appliance: ApplianceDto;
  detected: {
    type: ApplianceType;
    brand: string | null;
    model: string | null;
    confidence: number;
  };
}

// ---- Appliance scanner (analyze + save) ----
export interface AnalyzeApplianceFromImageRequest {
  /** Public URL the API can fetch (typically after S3 upload). */
  imageUrl: string;
}

export interface AnalyzeApplianceFromImageResponse {
  /** Three best type guesses (highest confidence first). */
  typeOptions: Array<{ type: ApplianceType; confidence: number }>;
  /** Gemini-derived best guess for brand/model (user can edit). */
  suggested: {
    type: ApplianceType;
    brand: string | null;
    model: string | null;
    /**
     * 0..1 — how confident the AI is in the `type` field above.
     * Lower values indicate the AI cannot reliably place this in the
     * supported {@link ApplianceType} enum.
     */
    confidence: number;
    /**
     * Free-text 1-3 word description of what the AI thinks it sees
     * (e.g. "Coffee maker", "Space heater", "Lamp"). Especially useful
     * when `type` falls back to `OTHER` — gives the user a meaningful
     * hint instead of just "OTHER".
     */
    categoryGuess?: string | null;
    /**
     * Coarser-grained bucket the device probably belongs to. Display-only.
     */
    broadCategory?: BroadCategory | null;
  };
}

export interface CreateApplianceRequest {
  roomId: string;
  imageUrl: string;
  type: ApplianceType;
  brand: string | null;
  model: string | null;
  nickname?: string;
  suggestedTasks?: SuggestedMaintenanceTask[];
}

export interface CreateApplianceResponse {
  appliance: ApplianceDto;
}

export type SuggestedMaintenanceTask = {
  title: string;
  description: string;
  cadenceDays: 1 | 7 | 30;
  estimatedMinutes: number;
  safetyWarnings: string[];
  whyItMatters: string;
};

export interface GetSuggestedMaintenanceTasksRequest {
  applianceType: ApplianceType;
  brand: string;
  modelId?: string;
  imageUrl?: string;
}

export interface GetSuggestedMaintenanceTasksResponse {
  tasks: SuggestedMaintenanceTask[];
}

// ---- Dashboard ----
export interface DashboardHomeResponse {
  user: UserDto;
  rooms: RoomDto[];
  upcomingTasks: MaintenanceTaskDto[];
  activeRepairSessionId: string | null;
}

// ---- Maintenance / Schedule ----
export interface MaintenanceTaskDto {
  id: string;
  applianceId: string;
  applianceNickname: string | null;
  applianceType: ApplianceType;
  title: string;
  description: string | null;
  /** Optional category tag used for special UI flows (e.g. DRYER_LINT_FILTER). */
  category: string | null;
  /** Optional target part for vision flows (e.g. lint_filter). */
  focusPart: string | null;
  dueDate: string;
  status: TaskStatus;
  estimatedMinutes: number | null;
  /** Recurrence interval in days; null for one-off tasks. */
  cadenceDays: number | null;
  /** Short, user-facing reason this task matters. */
  whyItMatters: string | null;
  /** Concise safety reminders for this specific task. */
  safetyWarnings: string[];
  /** "ai" if generated by Gemini for this appliance, "template" if static, "manual" if user-created. */
  source: 'ai' | 'template' | 'manual';
}

export interface ScheduleUpcomingResponse {
  tasks: MaintenanceTaskDto[];
}

// ---- Task actions (proactive system) ----
export interface CompleteTaskResponse {
  task: MaintenanceTaskDto;
  /** Auto-created next instance for recurring tasks; null for one-offs. */
  nextTask: MaintenanceTaskDto | null;
}

export interface SnoozeTaskRequest {
  /** How many days to push the due date forward. Defaults to 7 if omitted. */
  days?: number;
}

export interface SnoozeTaskResponse {
  task: MaintenanceTaskDto;
}

// ---- Vision (part detection) ----
export type PartDetection = {
  label: string;
  confidence: number; // 0..1
  /** Normalized bbox in 0..1 relative to the input image. */
  bbox: { x: number; y: number; w: number; h: number };
};

export interface DetectPartsRequest {
  imageUrl: string;
}

export interface DetectPartsResponse {
  detections: PartDetection[];
}

// ---- Media ----
export interface SignedUploadRequest {
  contentType: string;
  /** logical purpose: e.g. "appliance", "repair-step" */
  kind: 'appliance' | 'repair-step';
}

export interface SignedUploadResponse {
  uploadUrl: string;
  publicUrl: string;
  key: string;
  headers: Record<string, string>;
  expiresAt: string;
}

// ---- Repair ----
export interface StartRepairRequest {
  applianceId: string;
  symptom: string;
}

export interface RepairSessionDto {
  id: string;
  applianceId: string;
  status: RepairStatus;
  diagnosis: string;
  safetyWarnings: string[];
  currentStateId: StateId;
  currentState: RepairState;
  startedAt: string;
  endedAt: string | null;
}

export interface RespondRequest {
  /** Free text or selected option. */
  answer: string;
}

export interface RepairPhotoRequest {
  imageUrl: string;
}

export interface RepairTransitionResponse {
  session: RepairSessionDto;
  /** True if the latest input advanced (or completed) the machine. */
  advanced: boolean;
  /** For verify_photo: whether the photo passed verification. */
  photoPassed?: boolean;
  /** Free-text feedback to show the user (from the vision model). */
  feedback?: string;
}
